services:
  youtubee_front_end:
    build: front-end
    ports:
      - "1001:80"
      - "2001:443"
    environment:
      - YOUTUBEE_BACK_END_URL=https://youtubee.nex.sh:1001

  youtubee_back_end:
    build: back-end
    ports:
      - "2011:2011"
    environment:
      - YOUTUBEE_FRONT_END_URL=https://youtubee.nex.sh
      - PORT=2011