FROM node:18-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . .
ARG BACKEND_URL
ENV YOUTUBEE_BACK_END_URL=${BACKEND_URL}
RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/public /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]