FROM node:18-alpine as build-stage
ENV YOUTUBEE_BACKEND_URL https://192.168.4.101:1444
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/public /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]