FROM jrottenberg/ffmpeg:4.1-alpine AS ffmpeg
FROM node:18-alpine as build-stage
WORKDIR /app
COPY package*.json .
RUN npm i
COPY . .
COPY --from=ffmpeg / /
RUN mkdir /downloads
CMD ["npm", "run", "start"]